### PR TITLE
index.html: Added fake accounts section

### PR DESCRIPTION
**Pull request by sakshisangwan**
Added a section for fake accounts that are not managed by LinuxChix India.

### CODE REVIEW

**Comment by CuriousLearner** [comment]
I don't understand why are we always in a hurry to do things? Why do we want to promote someone?

**Review by utkarsh2102 — CHANGES_REQUESTED** [review]
Hey,
The branch should be `develop` and not `master`.
No PRs shall be accepted on the `master` branch.

**Comment by CuriousLearner** [comment]
I won't accept this PR on either branch.

I would first like to discuss the reason for these kinds of changes. If someone registers accounts on different platforms with the community name, then the community displaying those links would do more harm than good.

People would accidentally click on those and see them as official community links.

You can't stop people from doing bad things, but you can take a step back and think about what you're trying to do and first rationalize the decision considering the pros as well as cons.

@utkarsh2102 @sakshisangwan

**Comment by sakshisangwan** [comment]
Closing this PR since it was made after a discussion with few community members but later considering your (@CuriousLearner) point everyone agreed not to make these changes.

**Pull request closed without merging**
